// SETTINGS REDUCER ACTIONS
export const SET_LOADING = 'SET_LOADING';

// MODAL REDUCER ACTIONS
export const SET_MODAL = 'SET_MODAL';

// USER REDUCER ACTIONS
export const SET_USER = 'SET_USER';
export const REMOVE_USER = 'REMOVE_USER';
